apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: notebook
spec:
  template:
    spec:
      affinity: {}
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          name: notebook
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.quit_button=False
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          image: <>
          workingDir: /opt/app-root/src
