name: Notebook Image Build Landing Action
on:
  push:
    paths:
      - 'notebooks/**'
jobs:
  changed-notebooks:
    env:
      GH_TOKEN: ${{ secrets.NOTEBOOK_ACTION_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Get changed notebooks
        id: changed-notebooks
        uses: tj-actions/changed-files@v43
        with:
          dir_names: true
          files: notebooks/**
      - name: List changed files
        run: |
          for folder in ${{ steps.changed-notebooks.outputs.all_changed_and_modified_files }}; do
            echo "Changed notebooks: $folder"
            gh workflow run Build_Notebook_Image -f folder=$folder
          done
